kafka.bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=PLAIN
kafka.sasl.jaas.config=kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule required username='<KAFKA_USER_NAME>' password='<KAFKA_PASSWORD>';

confluent.schema.registry.url=https://psrc-zgxgq7p.us-east1.gcp.confluent.cloud
confluent.schema.registry.basic.auth.credentials.source=USER_INFO
confluent.schema.registry.basic.auth.user.info=<SCHEMA_REGISTRY_USER_NAME>:<SCHEMA_REGISTRY_PASSWORD>
