kafka.bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=PLAIN
kafka.sasl.jaas.config=kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule required username='4MFDPRDFINCDFBQZ' password='cfltC3Nq/hGnG7rolufdJiaaNhitmxSQlD05QPDDEZOZYLPaqFF/EIvVtM0a3q9w';

confluent.schema.registry.url=https://psrc-zgxgq7p.us-east1.gcp.confluent.cloud
confluent.schema.registry.basic.auth.credentials.source=USER_INFO
confluent.schema.registry.basic.auth.user.info=IIBN7RCM3BQ4AIVW:cfltPFXJcVac07dB3flxl+h3p1NRyD9Pq3NiOET9r1FL6fZiAnE75cXIlznHnj8g